### ISSUE TITLE
suggestion for the readme

### ISSUE THREAD

**Issue by YoelShoshan** [bastibe/transplant#12]
Hi,
I have a suggestion for the readme - you can add a part about making it run on windows.
This can save few precious minutes to the people intending to run it on windows.
It is also especially important since part of your library audience may be windows matlab users which are not necessarily l33t haxxors ;)

Here's a bunch of tips - you may think that some (or most) of this goes beyond the scope of your readme, but I think that if it helps people install and use it quickly, than why not :)

* Install zeromq from here:
http://zeromq.org/distro:microsoft-windows
"Stable Release 4.0.4" worked well for me.

* Copy libzmq-v90-mt-4_0_4.dll into libzmq.dll

* Make sure that matlab knows the path of this dll (I don't remember if I did this using the PATH env. variable, or by adding addpath('path/to/zeromq/bin') to matlabrc.m )

* Put addpath('path/to/transplant_library') in matlabrc.m

* Matlab doesn't always ship with a C/C++ compiler, In my case of Matlab 2014b x64 it didn't.
Matlab needs a compiler in order to load and use the zeromq binary DLLs, which is a C++ library. Note that it's needed for using matlab "LoadLibrary" function to load any C/C++ DLL.

* In the case that you don't have a compiler that Matlab knows, one of the options that you can do is download  Win 7 SDK.
https://www.microsoft.com/en-us/download/details.aspx?id=8279
Note that the sdk installer checks for .net framework 4, and in the likely case that you have a newer version it will not install.
You can trick it into installing with some simple registry trickery (*remember to restore it back after the installation is complete*)
Make sure that compilers are selected as a component to be installed.
Look at the accepted answer here for the registry trickery:
http://stackoverflow.com/questions/31455926/windows-sdk-setup-failure

* I had to change transplantzmq.h into this:
[transplantzmq.zip](https://github.com/bastibe/transplant/files/322800/transplantzmq.zip)
Due to typedef conflicts and unkown variable types.

* Now, manually run a *new* Matlab session, and verify that you can manually use LoadLibrary('lib
zmq.dll','transplantzmq.h') without getting any errors/warnings.

* You are ready to go!

**Comment by bastibe** [comment]
Thank you very much! This will indeed be very helpful to a lot of people.

I will incorporate these into the README later this week, and also update `transplantzmq.h` so that it works cross platform. This has been very helpful!

If you want to, I'd be grateful for a pull request as well.

**Comment by YoelShoshan** [comment]
Sure, will do - never done that before.
Open source world - here I come! XD

**Comment by YoelShoshan** [comment]
Done :)

**Comment by bastibe** [comment]
Very cool! Thank you so very much for your help!
