### ISSUE TITLE
Problem with from transplant_master import Matlab

### ISSUE THREAD

**Issue by vl13666** [bastibe/transplant#20]
Hello, i'm facing problem with importing Matlab class. I'm using python 2.7 and Matlab R2015b. 

transplant_master.py, line 446
    def __call__(_self, *args, nargout=-1):  
                                     ^
SyntaxError: invalid syntax

also had problem with line 133 from the same file
print(line.decode(), end='')
that i fixed by adding :  **from __future__ import print_function**   in the beggining of the file.

May be you have some suggestions about first problem?
Thanks in advance.

**Comment by bastibe** [comment]
Please try running Transplant in Python 3 and see if that fixes your problem.

**Comment by vl13666** [comment]
It works on python 3.4, but do you have any ideas how to fix it less radically and still use on python 2.7?

**Comment by bastibe** [comment]
Apparently, you can't mix `*args` and keyword arguments in Python 2. You can fix it by replacing the keyword argument with `**kwargs`, and pulling `nargout` out later.

**Comment by bastibe** [comment]
On further thought, the above change would complicate that function significantly. I would recommend using Python 3.
