### ISSUE TITLE
Matlab plot() and imagesc()

### ISSUE THREAD

**Issue by vl13666** [bastibe/transplant#21]
Did not find how to use this matlab commands with transplant. Can you give simple example on how to plot   1d numpy array with matlab.plot() and 2d with matlab.imagesc()? Of course there is a native matplotlib, but I personally prefer those Matlab functions, already use it with matlab's proprietary  python API engine.

**Comment by bastibe** [comment]
As stated in the README, you likely forgot to put an `matlab.drawnow()` into your code.
