### ISSUE TITLE
Some special characters from Matlab stdout are not transferred properly 

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#22]
This is a minor bug. 
When I use the code:
`cell = m.eval('{1 1 1}',nargout=0)`
Python returns:
```
ans =
  13 cell array
    [1]    [1]    [1]
```
The original Matlab output:
```
ans =
  1×3 cell array
    [1]    [1]    [1]
```
The '×' character disappeared somehow.

**Comment by bastibe** [comment]
This works fine on my machine. What is the output of `feature('DefaultCharacterSet')` on your machine?

**Comment by tsdev** [comment]
I get the following output in Matlab: `US-ASCII`.

**Comment by bastibe** [comment]
The problem is: That `×` is a unicode *Multiplication Sign*, which is not expressible in `US-ASCII`. Sadly, whenever Matlab can't guess your native encoding, it chooses `US-ASCII`. Set it to `UTF-8`, and everything will work correctly.

**Comment by tsdev** [comment]
I used the command:
`matlab.feature('DefaultCharacterSet','UTF8')`
However I still get special characters missing when using the command
`cell = matlab.eval('{1 1 1}',nargout=0)`
The return text is:
```
ans =
  13 cell array
    [1]    [1]    [1]
```

**Comment by bastibe** [comment]
You have to change some XML file somewhere inside Matlab to fix this. This is not something Transplant can address.

**Comment by bastibe** [comment]
Here is an explanation of how to do this:
http://bastibe.de/2015-04-15-unicode-in-the-matlab-command-line.html
