### ISSUE TITLE
Quitting Matlab connection

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#24]
At present the `.close` method closes the connection to Matlab. The problem is that this hides the Matlab command with the same name that closes figures (although the alternative `matlab.delete(handle)` can be still used of course). Also this allows to call `matlab.quit()` and `matlab.exit()`, which hangs transplant (probably by closing Matlab but without Transplant registering it). Would it be possible to change the Transplant `.close` method name to `exit()` and use `quit()` as alias? I understand this would break compatibility with older versions though.

**Comment by bastibe** [comment]
Very good point! I'll look into that.

**Comment by bastibe** [comment]
The latest revision changes `close` to `exit`, which should fix your issue. I have not overloaded `quit`, since it provides additional arguments that I can not reproduce in Transplant.

**Comment by tsdev** [comment]
Works fine! Thank you!
