### ISSUE TITLE
Calling Matlab module functions

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#25]
In Matlab functions can be defined within a module by placing them in a folder with name starting with +: e.g. `+myModule`. To call them in Matlab one has to use:
```
myModule.myFun()
```
This causes problem in transplant, as a simple `matlab.myModule.myFun()` won't work. I simple workaround could be that we define a symbol for the dot notation, for example calling `matlab.myModule__myFun()` where the `__` symbol would be translated to `.` in Matlab.

**Comment by bastibe** [comment]
Interesting. This is likely another special case of things-that-have-names that `exist` doesn't know about. I'll look into it.

**Comment by bastibe** [comment]
The latest release contains support for packages. Can you confirm that this is a solution for your issue?

**Comment by tsdev** [comment]
I made a file `myfun.m` under the folder `+mypackage` to test the new code. I get the following error when running `m.mypackage()`:
```
>>> m = Matlab()
>>> mpkg = m.mypackage()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/phys/transplant/transplant_master.py", line 492, in __getattr__
    raise err
  File "/Users/user/phys/transplant/transplant_master.py", line 484, in __getattr__
    return self._get_global(name)
  File "/Users/user/phys/transplant/transplant_master.py", line 93, in _get_global
    response = self.send_message('get_global', name=name)
  File "/Users/user/phys/transplant/transplant_master.py", line 165, in send_message
    response['stack'], response['identifier'], response['message'])
transplant.transplant_master.TransplantError: Undefined variable 'mypackage'. (TRANSPLANT:novariable)
Traceback (most recent call last):
  File "/Users/user/phys/transplant/transplant_remote.m", line 94, in transplant_remote
    error('TRANSPLANT:novariable' , ...
```
When I run the `m.what('mypackage')` function I get the following:
```
{'classes': [], 'm': ['myfun.m'], 'mat': [], 'mdl': [], 'mex': [], 'mlapp': [], 'mlx': [], 'p': [], 'packages': [], 'path': '/Users/user/Documents/temp/+mypackage', 'slx': []}
```
It seems that the MATLAB `what` command called on the name of a package does return a structure, but the `packages` field is empty. It only contains the package name when `what` is called on the name of the parent folder that is in the `path` string.

**Comment by bastibe** [comment]
Thank you for the detailed bug report! Indeed my initial implementation only worked for classes within packages.

The latest commit should fix that. It should now work for arbitrary Matlab files within packages, or even packages within packages.

Can you verify that I did it correctly this time?

**Comment by tsdev** [comment]
Works as expected! Thank you!
The implementation is really nice!

**Comment by bastibe** [comment]
Thank you!

As it turns out, many problems seem to be much easier to solve on the Python side than on the Matlab side. Matlab seems to be seriously lacking in expressivity when meta-programming.
