### ISSUE TITLE
Calling Matlab functions whose names are Python keywords

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#27]
It is not possible to call the `class()` Matlab command, as the name is forbidden in Python. Others, such as `lambda` could also cause a problem. I realise this is a very minor issue though :)

**Comment by bastibe** [comment]
Interesting problem. I'm not sure how to solve this elegantly.

However, there is a workaround: You can always access arbitrary names using Python's builtin `getattr`:

```python
import transplant
with transplant.Matlab() as m:
     _class = getattr(m, 'class')
    print(_class(3.14))
```

this will print `'double'`.

The more I think about this, the more I think that this is actually the proper solution. What do you think?
