### ISSUE TITLE
Win64: ctypes.util.find_library('zmq')) returns None (should be 'libzmq.dll'?)

### ISSUE THREAD

**Issue by Foucl** [bastibe/transplant#30]
Hi,

I can't get transplant to work on win64 according to the installation instructions. `transplant.matlab()` fails with 

```python
Traceback (most recent call last):

  File "<ipython-input-3-8cd221b830b5>", line 1, in <module>
    transplant.Matlab()

  File "C:\Users\chdan\Anaconda2\envs\mymu\lib\site-packages\transplant\transplant_master.py", line 425, in __init__
    raise RuntimeError('could not locate libzmq for Matlab')

RuntimeError: could not locate libzmq for Matlab
```

Simply changing https://github.com/bastibe/transplant/blob/master/transplant/transplant_master.py#L413 to `ctypes.util.find_library('libzmq.dll'))` resolves the issue on my machine and everything works as expected.

According to https://docs.python.org/3/library/ctypes.html#finding-shared-libraries, this is to be expected on windows:

> On Windows, find_library() searches along the system search path, and returns the full pathname, but since there is no predefined naming scheme a call like find_library("c") will fail and return None.
> 
> If wrapping a shared library with ctypes, it may be better to determine the shared library name at development time, and hardcode that into the wrapper module instead of using find_library() to locate the library at runtime.

**Comment by bastibe** [comment]
Thank you for finding and fixing this bug!

I added one more commit to make the guess-the-libname game a bit less cumbersome.

Could you check if our combined fixes solved your problem?

**Comment by Foucl** [comment]
yes, that works perfectly! thanks a lot for taking care of this so quickly. I'll go ahead and close this issue.

**Comment by bastibe** [comment]
Great! I pushed the update to pypi.

Thank you again!
