### ISSUE TITLE
How to hide Matlab Command Window

### ISSUE THREAD

**Issue by BinWang0213** [bastibe/transplant#38]
The transplant works nicely on my WIN7 64bit system. But when I active Matlab everytime as follows:
```
import transplant
matlab = transplant.Matlab()
```
A "Matlab Command Window" will comes up. 
![image](https://user-images.githubusercontent.com/20053787/27720349-bf47865e-5d1e-11e7-8506-88f16ab2eae0.png)
Is there any way to hide this window?

The possibile solution like this?
`Matlab(arguments=('-nodesktop', '-nosplash'......more?))`

**Comment by BinWang0213** [comment]
I have found the reference link for the arguments
https://www.mathworks.com/help/matlab/matlab_env/commonly-used-startup-options.html?searchHighlight=%2Fnosplash&s_tid=doc_srchtitle
So I changed arguments as follows:
`'-minimize','-nosplash', '-nodesktop'`
I just curious about how Matlab Enigine for Python hide all GUI.

**Comment by bastibe** [comment]
Very interesting! I didn't know that the Windows version of Matlab behaves this differently. Thank you for figuring this out.

I'll try to find a better way of handling this next week! Please ping me again on this issue if I forget!

**Comment by bastibe** [comment]
The current version of Transplant should auto-`-minimize` on Windows. Can you check that this solves your issue?

**Comment by bastibe** [comment]
> I just curious about how Matlab Enigine for Python hide all GUI.

The Matlab Engine for Python does not run the Matlab executable. Instead, it starts a [Matlab Engine](https://mathworks.com/help/matlab/matlab_external/introducing-matlab-engine.html). Transplant doesn't do this, because it would require an installed compiler on Windows, and wouldn't work over the network. Plus, handling external processes is much easier than handling external C library calls.

**Comment by BinWang0213** [comment]
Thanks for your updating and nice work. This lib is faster and better than Matlab Engine.
I think you should put the blog link (http://bastibe.de/2015-11-03-matlab-engine-performance.html) into readme.md. It is a very nice usage and performance comparsion.

The auto minimize works, but you should use `-minimize` rather than `minimize` in your code.
```
if not desktop:
            if '-nodesktop' not in arguments:
                arguments += '-nodesktop',
            if '-nosplash' not in arguments:
                arguments += '-nosplash',
            if '-minimize' not in arguments and sys.platform in ('cygwin', 'win32'):
                arguments += 'minimize',     
        if not jvm and '-nojvm' not in arguments:
            arguments += '-nojvm',
```

**Comment by bastibe** [comment]
Thank you for pointing out that error. 

> I think you should put the blog link (http://bastibe.de/2015-11-03-matlab-engine-performance.html) into readme.md. It is a very nice usage and performance comparsion.

That is probably a good idea. There's also a follow-up article about some further speed-ups half a year later: http://bastibe.de/2016-06-21-transplant-revisited.html
