### ISSUE TITLE
Can not Stopping Matlab properly in IPython(Jupyter Notebook) on Win7 64bit 

### ISSUE THREAD

**Issue by BinWang0213** [bastibe/transplant#39]
Environement: WIN7 64Bit  Anaconda 4.4.0
The IPython will be hold in "Busy" even I have stopped Matlab properly (Figure below). In "Busy" status, I can not run any other code anymore even I interupted the kernel. 
![image](https://user-images.githubusercontent.com/20053787/27772242-ba5929a2-5f23-11e7-8b54-55207cadeb03.png)

Sample Code:
`import transplant`
`matlab = transplant.Matlab()`
`matlab.exit()`

**Comment by bastibe** [comment]
If you start Matlab without `-minimize`, do you get any error messages in the Matlab console window?

**Comment by BinWang0213** [comment]
Actually, the matlab can exit properly (when I run `matlab.exit()` ) without any error message.
But the IPython (Jupyter Notebook) seems didn't knew it. It was hold in "Busy" status.

**Comment by bastibe** [comment]
Have a look at [matlab.exit](https://github.com/bastibe/transplant/blob/master/transplant/transplant_master.py#L133). It tells Matlab to shut down (`self.send_message('die')`), then waits for the Matlab process to finish (`self.process.wait()`).

You said that `exit` does not return. This means that `self.process.wait()` does not return. Which means, Matlab does *not* exit properly. Something on the Matlab side is still running. Can you check in the Task Manager if Matlab is still running, and see if `exit` returns when you kill Matlab using the Task Manager?

**Comment by BinWang0213** [comment]
I just test it based on your suggestion. 
1. Task Manager Test
After run `(matlab.exit())` "matlab.exe" disappeared from the Task Manager immediately. The IPython still be hold

2.  Library transplant_master.py Modification Try
I even try to "print" something to indicate the "blocking" location. It is very strange that I didn't get any information from the IPython. 

```
    def __exit__(self, exc_type, exc_value, traceback):
        print("Killing Matlab-1...")
        self.exit()

    def exit(self):
        """Close the connection, and kill the process."""
        print("Killing Matlab-2...")
        if self.process.returncode is not None:
            return
        self.send_message('die')
        self.process.wait()
        print("Done...")

    def __del__(self):
        """Close the connection, and kill the process."""
        print("Killing Matlab-3...")
        self.exit()
```

**Comment by BinWang0213** [comment]
Finally Resolved:
I changed the stop function from `exit()` to `KillMatlab()`. The problems fixed right away. So I think the matlab also have a exit() which conflict with transplant lib.

![image](https://user-images.githubusercontent.com/20053787/27798315-6c1b933e-5fd6-11e7-94a2-43f0710ce6c1.png)

**Comment by bastibe** [comment]
I don't understand this, and can't reproduce it, either. What version of Transplant and Python are you running on what operating system?

`exit` should call `Matlab.exit`, then `TransplantMaster.exit`. At no point should `Matlab.__getattr__('exit')` be called (which would resolve to Matlab's `exit` function.

**Comment by BinWang0213** [comment]
I don't konw how to determine the Transplant version.
Operating system: Win7 64bit
Python: 'Python 3.5.3 |Anaconda 4.4.0 (64-bit)|
Transplant: I have compared the `transplant_master.py` between github and local one in sublime (figure below). The only difference is my modification in the last comment. So I think my Transplant is the latest one.

![image](https://user-images.githubusercontent.com/20053787/27799048-4dcedd2a-5fd9-11e7-84db-1778b1dd71f5.png)

**Comment by bastibe** [comment]
Then it is the most current version. Thank you for checking.

Could you do me a favor and check if `Matlab.__getattr__` is called when you run `Matlab.exit` on your computer? (Just add a print statement to `__getattr__` and see if it prints during `exit`)

I tried to recreate this bug on my Windows machine and my macOS machine, and I can't reproduce it.

**Comment by BinWang0213** [comment]
It is still doesn't print anything. This is the results:
![image](https://user-images.githubusercontent.com/20053787/27800252-2827037c-5fde-11e7-8a3b-2dd10fdf8831.png)

This is a very strange bug that you even can not reproduce it. I think you can added a additional exit() function with a different name, like `exit_matlab()`, into `transplant_master.py`. If someone have a similar problem, they can call `exit_matlab()` instead.

**Comment by bastibe** [comment]
Thank you very very much for helping me to debug this problem.

Regarding your suggestion, I am not convinced that the issue is a naming conflict within the `exit` method. If this were the case, you should be seeing `__getattr__` firing. 

We can go one step farther, though. Whenever Transplant wants to invoke a function in Matlab, it does so through `_call`. Could you check if `Matlab._call` or `TransplantMaster._call` is invoked during `Matlab.exit`? If these are not invoked, then the problem definitely lies elsewhere.

**Comment by BinWang0213** [comment]
Still not invoke. This is the results.
![image](https://user-images.githubusercontent.com/20053787/27801869-ff8ddf28-5fe5-11e7-82bb-be5421568467.png)

If you have some idea to try, please let me konw.

**Comment by bastibe** [comment]
I have no idea what is happening, there. At least it does not seem to call Matlab's `exit` function. If you Ctrl-C while it is hanging in `mlab.exit`, what is the stack trace?

**Comment by indivisibleatom** [comment]
#47
