### ISSUE TITLE
Error when Matlab function does not exist

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#41]
I am using OSX 10.12 with Matlab R2017a and Python 3.6.0 with transplant installed with pip. When I execute a matlab function that does not exist, I get a long error stack that contains no information on what does went wrong. For example executing:
`mlab.wrongfunction()`
I get the following error:
```
>>> mlab.wrongfunction()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/transplant/transplant_master.py", line 501, in __getattr__
    return self._get_global(name)
  File "/usr/local/lib/python3.6/site-packages/transplant/transplant_master.py", line 92, in _get_global
    response = self.send_message('get_global', name=name)
  File "/usr/local/lib/python3.6/site-packages/transplant/transplant_master.py", line 162, in send_message
    trace += '    ' + open(frame['file'], 'r', errors='replace').readlines()[int(frame['line'])-1].strip(' ')
IndexError: list index out of range
```
Would it be possible to return the error from Matlab:
`Undefined function or variable 'wrongfunction'. `

**Comment by bastibe** [comment]
I can't reproduce this problem. On my computer, it correctly raises `TransplantError: Undefined variable 'wrongfunction'. (TRANSPLANT:novariable)`. 

This might be related to your compilation. To render the stack trace, Transplant reads the original source files, which I guess are not available in your setup. Could that be the source of your problem?

**Comment by tsdev** [comment]
As always, you are right! When I run my code without compilation, it works with transplant. Now I am trying to call a compiled application with transplant. As far as I understand, the compiled code gets decompressed into a temporary folder containing the full folder structure with all m-files converted to p-code. Probably the p-code is that causes the problem.

If you have any idea where to look in your code that would greatly help my debugging. Also might be a cause for the problem is that there is no doc/help functions in the compiled code and all documentation is removed.

Thanks!

**Comment by bastibe** [comment]
The problem originates exactly where the stack trace puts it: line 162 in transplant_master.py. I'll walk you through the chain of events:

`send_message` is what prompts Matlab to execute some function, and receives the function's return values or error messages. Line 148 sends the function to Matlab for execution, line 149 receives the results. If the results are values, they are returned. If an error occurred on the Matlab side, `response['type']` is set to `error`, and the stack trace is saved in `response['stack']`, which triggers line 154.

What follows is Python trying to print the stack trace as part of the `TransplantError` error message. Particularly, line 159 walks the stack trace and prints each entry in the stack trace. Each entry in the stack trace consists of a file name, a line number, and a function name. In Python, stack traces typically print the contents of the line in question, thus, this code tries to read the file's contents and extract the line that caused the error. This breaks in your case.

In my experiments, stack frames from P-files contain a file name that ends with `.p`, which are explicitly not printed by Transplant (line 161). In your case however, something different seems to be happening. To analyze your problem, could you tell me the values of `frame['file']` and `frame['line']` at the time when the error occurs?

**Comment by tsdev** [comment]
So, I have the following response when transplant crashes with a compiled Matlab code:
```
{
'identifier': 'TRANSPLANT:novariable',
'message': "Undefined variable 'swpref'.",
'stack': [
   {'file': '/Users/user/Library/Application Support/.mcrCache9.2/pyspin2/Users/tothsa/spinw_git/external/transplant/transplant_remote.m',
   'line': 94.0,
   'name': 'transplant_remote'}, 
   {'file': '/Users/user/Library/Application Support/.mcrCache9.2/pyspin2/pyspinw/pyspinw.m', 
   'line': 28.0, 
   'name': 'pyspinw'}], 
'type': 'error'}
```
I figured out what the problem was. The error stack that is returned from Matlab contains references to lines in .m files. However these .m files are in reality p-files however with the extension .m. The files are found in a temporary folder where they are unpacked when I run the compiled code. I made a workaround in the transplant_remote.m. I added to the compiled code an additional folder with the Matlab source code and changed the error stack file references to point to this folder.

**Comment by bastibe** [comment]
OK, pushed a bug fix e6b1d79 that should fix your problem. Can you check that this solves your problem?

**Comment by tsdev** [comment]
Thanks for quick response! This seems to be an easy and simple fix and should solve the problem. All good. In my own project I will go forward with rewriting the error stack as it provides more informative errors in Python. I don't see a need to add my solution to your base code. I thinks this could be closed.

**Comment by bastibe** [comment]
Yes, I guess your application is a special case. Anyway, thank you for the debugging help. This kind of thing is always fun.
