### ISSUE TITLE
Transplant with Python2

### ISSUE THREAD

**Issue by tsdev** [bastibe/transplant#42]
I tried to import transplant on Python 2.7.13 but I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tothsa/.pyenv/versions/2.7.13/lib/python2.7/site-packages/transplant/__init__.py", line 1, in <module>
    from .transplant_master import Matlab, TransplantError, MatlabStruct
  File "/Users/tothsa/.pyenv/versions/2.7.13/lib/python2.7/site-packages/transplant/transplant_master.py", line 124
    print(line.decode(), end='')
                            ^
SyntaxError: invalid syntax
```

Is transplant planned to run on Python 2.7?

**Comment by bastibe** [comment]
No, transplant is not supposed to run on Python 2.7.

**Comment by tsdev** [comment]
Ok, thanks. It might be good to note that in the documentation.

**Comment by bastibe** [comment]
I added a note to the README. A better solution would specify the python version in setup.py, so that you couldn't even install Transplant on Python 2.7, but I can't figure out how to do that.

**Comment by bastibe** [comment]
As of the latest version, Transplant should neither run nor install on Python 2.7.
