### ISSUE TITLE
example code not working (newbie here)

### ISSUE THREAD

**Issue by nbecker** [bastibe/transplant#54]
>>n, m = matlab.size([1, 2, 3])

ValueError: not enough values to unpack (expected 2, got 1)

>>matlab.size([1, 2, 3])
Out[78]: array([[ 1.,  3.]])

I guess this is just a documentation error?

This is python 3.6

**Comment by bastibe** [comment]
Oh fun! Thank you for finding that error!

It is indeed a documentation error. As you can see from the result is actually correct (`1, 3`), but as is typical in Matlab, the result is returned as a 2D matrix as opposed to a Numpy-style 1D array. This breaks the value unpacking.

    [[n, m]] = matlab.size([1, 2, 3])

works correctly. I changed the documentation accordingly.
