### ISSUE TITLE
Function handles

### ISSUE THREAD

**Issue by simonward86** [bastibe/transplant#59]
Dear Bastian,

Is there a way of using function handles in function arguments? 

For example in matlab syntax:  
`result = gateway_func('func',@func,'vars',xx,'additional',yy);`
I've tried:  
`result = matlab. gateway_func('func',matlab.str2func('func'),'vars',xx,'additional',yy)` 
Without success as the matlab_function object cannot be transferred.

Any help or suggestions would be great.

Simon

**Comment by bastibe** [comment]
Function handles can be passed back to Matlab, i.e.
```python
result = matlab.gateway_func('func', matlab.func, 'vars', xx, 'additional', yy)
```
As you know, `matlab.func` will create a Python object that calls the Matlab function `func`. However, just like any other Matlab object, Transplant will convert it back to the original Matlab function if you pass it back to Matlab.

By the way, we recently added a fun new feature that allows you to write that same call as
```python
result = matlab.gateway_func(func=matlab.func, vars=xx, additional=yy)
```
Transplant now auto-converts keyword arguments to Matlab-style key-value lists.

**Comment by simonward86** [comment]
Thanks for the response. I've tried as suggested but still can't get it to work. The error is:

`TypeError: can't serialize <transplant.transplant_master.Matlab._decode_function.<locals>.matlab_function object at 0x7f5444531828>`

It seems to be a problem with Transplant converting function object from python back into Matlab . 
I've chosen a simple example which shows the error: 

`matlab.feval(matlab.plus,1.,2.)`

**Comment by bastibe** [comment]
Thank you for your bug report! This indeed does not work.

I'll look into it later today.

**Comment by bastibe** [comment]
The latest commit should fix your issue. Can you confirm that the fix works?

**Comment by simonward86** [comment]
Thanks for the speedy fix, it works for both my test case and real case.

**Comment by bastibe** [comment]
Cool! I uploaded the new version to PyPi.
