### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by toddrme2178** [bastibe/transplant#61]
I am trying to package transplant for openSUSE. However, there is no license file I can find, either in the github or tarball. In order for people to know how they can use your code it is really important to have a license file. Would it be possible to add one? Thank you.

**Comment by bastibe** [comment]
Thank you for your efforts!

The license is part of the README (at the end). Transplant is licensed under the terms of the BSD 3-clause license.

Is this sufficient, or do you require a *separate* license file?
