### ISSUE TITLE
Returns only 1 value from output of mex function

### ISSUE THREAD

**Issue by sirgogo** [bastibe/transplant#63]
Hi, 
First off, I just want to say, this is great library.

My issue occurs when calling a mex function from python as:
`tmp = eng.mymexfun(*args)`

I am expecting two output arguments, both of size 1683x2250, but instead I am receiving only 1. This same call works fine if I use a Matlab-function from a .m file. Could it be something to do with how the values are read out from main memory? (I don't know much about the implementation, just postulating here).

Unfortunately I can't share my mex function, but I know that it works because it works correctly when called from matlab, with the same exact variables loaded.

Any ideas? Thanks in advance!

**Comment by sirgogo** [comment]
Thanks this did it! Sorry if I missed it in the documentation earlier.

**Comment by bastibe** [comment]
No problem.
