### ISSUE TITLE
How to use transplant.MatlabStruct(dict)

### ISSUE THREAD

**Issue by tombadmanship** [bastibe/transplant#65]
Hello, will you please post an example of how to populate this object?

**Comment by bastibe** [comment]
build your dict, then wrap it in `transplant.MatlabStruct` before passing it to Matlab.

```python
x = dict(...) # build your dict as you normally would
matlab.disp(transplant.MatlabStruct(x)) # wrap it, and pass to Matlab
```

**Comment by tombadmanship** [comment]
I see - thank you for your response.
