### ISSUE TITLE
transplant crippled on msgpack-python 0.6.0 (max_bin_len change)

### ISSUE THREAD

**Issue by jooh** [bastibe/transplant#67]
Thanks for a great tool. Transplant crashes on large matlab variables when installed with msgpack 0.6.0 due to [a change to the max_bin_len default](https://github.com/msgpack/msgpack-python/issues/295). See also [related issue on spacy here](https://github.com/explosion/spaCy/issues/2995).

Downgrading to msgpack-python 0.5.6 fixed it for me. A quick fix would be to pin to <= 0.5.6.

**Comment by bastibe** [comment]
Thank you for raising awareness for this issue! I was unaware of this, but apparently many people are angry about this change!

Can you check if #68 fixes this issue?

**Comment by bastibe** [comment]
Cool!
