### ISSUE TITLE
interacting with figures/plots

### ISSUE THREAD

**Issue by bsxfun** [bastibe/transplant#69]
I managed to get as far as plotting some data (making use of the 'drawnow' trick), but then I could not interact with the plot at all in the usual way Matlab allows (zoom, etc.).  Each button I press does nothing and the menu items (File, Edit, View, etc.) don't react to button presses either.

I'm wondering if it's just me or is this documented behaviour?

I'm running it through iPython on Linux, and I'm getting this behaviour with Matlab 2015a and 2018b.  Can give more details if necessary.

**Comment by bastibe** [comment]
Try running `matlab.pause(0)` repeatedly or `matlab.uiwait(figure_handle)` to give Matlab time to process user input.

**Comment by bsxfun** [comment]
matlab.uiwait(figure_handle) fixed it!  many thanks for the speedy reply!

i would even suggest that 'trick' could be added to the readme.

**Comment by bastibe** [comment]
Cool! Would you like to create a pull request that adds it to the README?
