### ISSUE TITLE
connect to existing matlab session

### ISSUE THREAD

**Issue by bsxfun** [bastibe/transplant#70]
I know that closing Matlab from iPython-launched transplant connection is currently an open problem, so I'm wondering if there's a recommended way to connect to an open transplant-Matlab-connection?

that means, effectively, you could run a script twice using the same connection.  the first time it would open, and the second time it would re-use the same connection.  I guess that means you have to use '%run -i' to start with...

**Comment by bastibe** [comment]
You could re-use an existing global variable that contains your `Matlab` instance. As long as this variable doesn't go out of scope or is explicitly closed, it will not terminate.

Actually, closing Matlab is no problem as far as I am aware of, so long as you close it explicitly. The only issue is that IPython can prevent variables from going out of scope, and therefore from being garbage collected (which would implicitly close the connection). But `Matlab.close()` should always work.

**Comment by bsxfun** [comment]
ok thanks... for the record my implemented solution is:

try:
    eng.disp("existing connection")
except:
    eng = transplant.Matlab()
    eng.disp("new connection")

and I'm just running with '%run -i', but I didn't need a global variable.  If you have a more recommended implementation/solution let me know.

**Comment by bastibe** [comment]
Cool, so this solved your problem?

**Comment by bsxfun** [comment]
my hack solved the problem, but not sure it's optimal... anyway, i'll close this issue.. 

thanks for the help and great work!
