### ISSUE TITLE
Matlab package is not found when there are directories with the same name

### ISSUE THREAD

**Issue by dani-l** [bastibe/transplant#81]
After spending some time trying to call a Matlab function in a package and wondering why I always got an UndefinedFunction error, I finally realized that this was actually caused by the current working directory having the same name as the package.

The same thing seems to happen if the current working directory contains another directory with the same name as the package. I didn't check further to see if this also applies to any directory in Matlab's path.

In `Matlab.__getattr__`, there is a very specific check for detecting packages: `if not (err.identifier == 'TRANSPLANT:novariable' and packagedict):`. When the error appears, `err.identifier` was `MATLAB:UndefinedFunction` instead of `TRANSPLANT:novariable`.

Here is a minimum example that should make it possible to reproduce the bug just by pasting the commands:
~~~
% mkdir -p transplanttest/projectname/matlab/+projectname/
% echo -e "function []=foobar()\ndisp(42)" > transplanttest/projectname/matlab/+projectname/foobar.m
% python3 -c "import transplant; m=transplant.Matlab(); m.addpath('transplanttest/projectname/matlab'); m.projectname.foobar()"
...
    42
% cd transplanttest
% python3 -c "import transplant; m=transplant.Matlab(); m.addpath('projectname/matlab'); m.projectname.foobar()"
...
transplant.transplant_master.TransplantError: Undefined function or variable 'projectname'. (MATLAB:UndefinedFunction)
...
% cd projectname
% python3 -c "import transplant; m=transplant.Matlab(); m.addpath('matlab'); m.projectname.foobar()"
...
transplant.transplant_master.TransplantError: Undefined function or variable 'projectname'. (MATLAB:UndefinedFunction)
...
% cd matlab
% python3 -c "import transplant; m=transplant.Matlab(); m.projectname.foobar()"
...
    42
~~~

**Comment by bastibe** [comment]
Thank you for your bug report.

If I understand this issue correctly, there is a bug in [`get_global`](https://github.com/bastibe/transplant/blob/master/transplant/transplant_remote.m#L86) that produces an error other than `TRANSPLANT:novariable`. As far as I can tell this means that either `which('projectname')` or `exist('projectname')` produced an error in Matlab.

If true, that is a bug in Matlab, not Transplant. (Am I understanding this correctly?)

That said, I'd be grateful for a pull request that fixes this issue, if it can be done on the Matlab side, and without adding a large performance overhead.

**Comment by dani-l** [comment]
Thanks for the pointers. From a quick look, it seems like in the failing cases, `exist('projectname')` returns 7 ("name is a folder") instead of 0.

If I find the time for it, I will try to investigate further and create a pull request.

**Comment by bastibe** [comment]
That would be greatly appreciated.

**Comment by dani-l** [comment]
I did spend some time looking into it. The good news it that a simple

~~~diff
-                    existance = existance | any(which(msg('name')));
+                    existance = ~any(existance == [0, 7]) | any(which(msg('name')));
~~~

fixes the bug for me.

The bad news is that I am quite irritated by the next few lines of code:

~~~matlab
existance = evalin('base', ['exist(''' msg('name') ''')']);
~~~
returns an number between 0 and 8, then
~~~matlab
existance = existance | any(which(msg('name')));
~~~
turns this into a logical value, i.e. it is either 0 or 1. A few lines later
~~~matlab
elseif any(existance == [2, 3, 5, 6]) | any(which(msg('name')))
~~~
is checked, and the first part can never be true as `existance` is always 0 or 1.

I am not sure if I am missing something or the code is indeed broken. I feel like applying my fix without fixing the rest of this is not the right approach but I don't understand the transplant internals enough for a proper fix.

**Comment by bastibe** [comment]
I wish I could help you. But at the moment, I am stuck at home, without access to Matlab.

But if that fix works, and the rest of the test suite still runs, I would assume it is good, and I would gratefully accept a pull request.

**Comment by dani-l** [comment]
any news on this?

**Comment by bastibe** [comment]
I am terribly sorry for the late response. Your PR somehow fell off my radar. Again, my apologies.

Thank you very much for dealing with the issue quickly and efficiently, though!

**Comment by disadone** [comment]
I use pip3 to install transplant. I have a similar issue, it seems the topic discussed here fixed the bug.
However, I have a package already "setpath" in matlab gui enviroment. It works fine in my matlab2019a, while using transplant by
`matlab.bads([myargument])`
it returns

> Exception has occurred: TransplantError
> Undefined variable 'bads'. (TRANSPLANT:novariable)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/transplant/transplant_remote.m", line 94, in transplant_remote
>     error('TRANSPLANT:novariable' , ...

Many thanks.

**Comment by dani-l** [comment]
Slightly off-topic here, but do you have plans to release a new version that includes the fix at some point? Being able to install a version that includes the fix from PyPI would make things easier for me.

**Comment by bastibe** [comment]
Sorry about that. I'll try to do it tomorrow morning.

**Comment by dani-l** [comment]
Thanks! :) Any update on this?

**Comment by bastibe** [comment]
Sorry about that. I had an accident that all made desk work all but impossible.

But I just uploaded the release. Thank you for your patience.

**Comment by dani-l** [comment]
Thank you!
