### ISSUE TITLE
cannot find libzmq on windows 10

### ISSUE THREAD

**Issue by hardmstar** [bastibe/transplant#86]
Hi, this module helps me a lot on liunx, but when I switch platform to windows 10, function `Matlab._locate_libzmq()` in `transplant_master.py` didn't work, `raise RuntimeError('could not locate libzmq for Matlab')`.

I find things went wrong in row 695 `search_dirs = ((os.getenv('PATH') or '').split(':') +` in `transplant_master.py`. `PATH` variable should be like `"C:\Program Files (x86);C:\python"`, but when choose `':'` as the split parameter, `PATH` values will be split into `['C', '\\Program Files (x86);C', '\\python']`, thus it cannot find `*zmq*.dll` from `PATH` variable. 
```python
        # row 693-697 in transplant_master.py
        elif sys.platform == 'win32' or sys.platform == 'cygwin':
            # according to https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx
            search_dirs = ((os.getenv('PATH') or '').split(':') +
                           ['C:/Program Files/ZeroMQ*/bin'])
            extension = '.dll'
```

Then I change `.split(':')` to `.split(';')`, and the `libzmq` can be find, the module works.

So could you please tell me why use `':'` as the split parameter but not `';'`?

**Comment by bastibe** [comment]
Probably a typo. Would you like to contribute the fix as a pull request?

**Comment by hardmstar** [comment]
Sure, I've post a pull request, but this commit only fix win32 or cygwin split parameter, linux and darwin not included.


| |
Joy Lee
|
|
wanpi-111@163.com
|
签名由网易邮箱大师定制
On 7/29/2020 15:12，Bastian Bechtold<notifications@github.com> wrote：

Probably a typo. Thank you for finding it! Would you like to contribute the fix as a pull request?

**Comment by bastibe** [comment]
Great! Linux and darwin do use `:` as a path separator. That's probably where I got the typo from. I wonder why that didn't break my test suite. Perhaps I had the DLL in the very first entry or something like that.

**Comment by hardmstar** [comment]
Agree with you. This is a brilliant work!
