### ISSUE TITLE
Error loading libzmq

### ISSUE THREAD

**Issue by haaabb** [bastibe/transplant#99]
After I use the command "matlab = transplant.Matlab()" in Pycharm, the error "Error loading libzmq" occur in matlab command window.

Error in the command window:
Error loading libzmq,no supported compiler found.

The versions of my matlab and python are 2021a and 3.7, and I use Win10.
I have installed zeromq with anaconda, am I using the wrong version of matlab?

Thank you

**Comment by bastibe** [comment]
I think you'll have to install a compiler first. Matlab has one in its app store thing, if I remember correctly.

**Comment by haaabb** [comment]
Thanks you！ it is finally working.
